#version of docker compose syntax to be used
#version: "3.9"


services:
#name of the service that will run the docker file
  app:
  # Specifies that the Docker image should be built using the current directory ('.').
  # The root directory is the build context.
    build:
      context: .
      # Pass build-time arguments to the Dockerfile
      args:
         # Indicates that this build is for development purposes
        - DEV=true

    # Port mappings: maps port 8000 on the local machine to port 8000 inside the Docker container.
    # This allows access to the application from the host machine.
    ports:
      - "8000:8000"

    # Volume mappings:
    # Syncs the 'app' directory on the host machine with the '/app' directory inside the Docker container
    # This allows live updates to reflect in the container during development
    # This also happens vice versa
    volumes:
      - ./app:/app

    # Command to run the service when the container starts.
    # Here, it runs the Django development server on all network interfaces.
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    
    # Define environment variables required to connect to the database
    environment:
      # Use 'db' as the hostname to connect to the database service
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme

    depends_on:
      # Specifies that the 'app' service depends on the 'db' service
      # Ensures that the database starts before the application
      # If the 'db' service fails, the 'app' service will not start
      - db

# Add a database service to the Docker Compose configuration
  db:
    # Use PostgreSQL version 13 with a lightweight Alpine Linux image
    image: postgres:13-alpine
    volumes:
      # persist database data in the defined volume to avoid data loss across container restarts
      - dev-db-data:/var/lib/postgresql/data
    environment:
      # Set three environment variables required for PostgreSQL:
      # 1. POSTGRES_DB: Defines the name of the initial database created at startup
      # 2. POSTGRES_USER: Sets database username
      # 3. POSTGRES_PASSWORD: Sets the password for the database user
      # These credentials are used for local development only and should not be used in production
      #    i.e. this only runs on the local machine and won't be publicly available
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  # Define a named volume to persist database data
  dev-db-data: