# Generated by Django 3.2.25 on 2025-07-08 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250708_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingreidents',
            new_name='ingredients',
        ),
    ]
