# 3 dashes at the top signify it's a yml file
---

name: Checks

#trigger telling GitHub actions to run when code is pushed
on: [push]

#specify jobs to run
#steps are executed in order
#if any of the commands fail the entire job fails


# Define a job named "test-lint"
jobs:
  test-lint:
    # Name of the job as it will appear in the GitHub Actions UI
    name: Test and Lint
    # Specifies the operating system the job will run on (Ubuntu 20.04 in this case)
    runs-on: ubuntu-20.04

    # List of steps to be executed in this job
    steps:
      # Step 1: Log in to Docker Hub
      # This is the human-readable name that will be visible on the GitHub action interface
      - name: Login to Docker Hub
        # Use the Docker Login Action to authenticate with Docker Hub
        # An action is a docker container and configuration set up to perform a certain task
        # using the login action in docker. version 1 {@v1}
        uses: docker/login-action@v1
        # Provide the Docker Hub username and password/token from GitHub Secrets
        # These are passed into Docker Login action and will login to docker with the given credentials
        with:
          # Docker Hub username stored in GitHub Secrets
          username: ${{ secrets.DOCKERHUB_USER }}
          # Docker Hub token (or password) stored in GitHub Secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 2: Checkout the code from the repository
      - name: Checkout
        # Use the Checkout Action to clone the repository code into the runner
        # The actions/checkout action clones the GitHub repo to $GITHUB_WORKSPACE to achieve various jobs,
        # such jobs include building, testing, and deploying the code. Without checkout, these can't be done
        uses: actions/checkout@v2

      # Step 3: Run unit tests
      - name: Test
        # Execute a command to run unit tests using Docker Compose
        # Explanation:
        # - `docker-compose run --rm`: Starts a new container using Docker Compose and removes it after execution
        # - `sh -c "python3 manage.py test"`: Runs the command to execute unit tests in the container
        run: docker compose run --rm app sh -c "python3 manage.py wait_for_db && manage.py test"

      # Step 4: Run linting
      - name: Lint
        # Execute a command to run linting using Docker Compose
        # Explanation:
        # - `docker-compose run --rm`: Starts a new container using Docker Compose and removes it after execution
        # - `sh -c "flake8"`: Runs the Flake8 linter to check for code style and syntax issues
        run: docker compose run --rm app sh -c "flake8"